# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         UMLS-Similarity
version:      0.17
version_from: lib/UMLS/Similarity.pm
installdirs:  site
requires:
    UMLS::Interface:               0.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
