--- #YAML:1.0
name:               UMLS-Similarity
version:            0.99
abstract:           A suite of Perl modules that implement a number 
author:
    - Bridget McInnes <bthomson@cs.umn.edu>, Ted Pedersen <tpederse@d.umn.edu>, Serguei Pakhomov <pakh0002 at umn.edu>, Ying Liu <liux0395@umn.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Path:           2.08
    File::Spec:           3.31
    Lingua::Stem:         0.84
    Text::NSP:            1.17
    Text::OverlapFinder:  0.02
    UMLS::Interface:      0.101
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
